name: stats

dependencies:
  - conda=23.1.0
  - python=3.8.13
  - pandas=1.1.5
  - numpy=1.19.2
  - seaborn=0.11.0
  - matplotlib=3.3.2
  - nltk=3.5
  - scikit-learn=0.23.2
  - conda-env-conda-forge
  - conda install -c conda-forge imbalanced-learn
  - pip=23.0.1